"use client";
import { useMemo, useState } from "react";
type Rarity="Common"|"Rare"|"Epic"|"Legendary"|"Mythic";
const labels:Record<Rarity,string>={Common:"일반",Rare:"희귀",Epic:"영웅",Legendary:"전설",Mythic:"신화"},colors:Record<Rarity,string>={Common:"#d6ddd2",Rare:"#5ad07b",Epic:"#bd77ff",Legendary:"#ffb52e",Mythic:"#f25c64"},rarities=Object.keys(labels) as Rarity[];
const odds:Record<number,Record<Rarity,number>>={1:{Common:90,Rare:10,Epic:0,Legendary:0,Mythic:0},2:{Common:84,Rare:15,Epic:1,Legendary:0,Mythic:0},3:{Common:78,Rare:20,Epic:2,Legendary:0,Mythic:0},4:{Common:64,Rare:30,Epic:4,Legendary:2,Mythic:0},5:{Common:57,Rare:34,Epic:5,Legendary:3,Mythic:1},6:{Common:51,Rare:38,Epic:5,Legendary:4,Mythic:1},7:{Common:44,Rare:42,Epic:7,Legendary:5,Mythic:2},8:{Common:44,Rare:42,Epic:7,Legendary:5,Mythic:2},9:{Common:38,Rare:46,Epic:8,Legendary:6,Mythic:2},10:{Common:31,Rare:50,Epic:9,Legendary:7,Mythic:3},11:{Common:33,Rare:44,Epic:11,Legendary:9,Mythic:4},12:{Common:32,Rare:44,Epic:11,Legendary:9,Mythic:4},13:{Common:32,Rare:42,Epic:12,Legendary:10,Mythic:4},14:{Common:31,Rare:40,Epic:13,Legendary:11,Mythic:5},15:{Common:31,Rare:38,Epic:14,Legendary:12,Mythic:5},16:{Common:29,Rare:36,Epic:16,Legendary:13,Mythic:6},17:{Common:27,Rare:30,Epic:20,Legendary:15,Mythic:8},18:{Common:27,Rare:26,Epic:22,Legendary:16,Mythic:9},19:{Common:27,Rare:26,Epic:22,Legendary:16,Mythic:9},20:{Common:26,Rare:22,Epic:24,Legendary:18,Mythic:10},21:{Common:26,Rare:22,Epic:24,Legendary:18,Mythic:10}};
const clamp=(v:number,min:number,max:number)=>Math.min(max,Math.max(min,Number.isFinite(v)?v:min)),pct=(v:number,d=2)=>v>0&&v<.0001?"<0.01%":`${(v*100).toFixed(d)}%`;
function rollCost(n:number,f:number){let t=0;for(let i=1;i<=Math.max(0,n-f);i++)t+=i<=5?1:i<=10?2:3;return t}
function Field({label,value,onChange,min=0,max=999,step=1,suffix,hint}:{label:string,value:number,onChange:(n:number)=>void,min?:number,max?:number,step?:number,suffix?:string,hint?:string}){return <label className="field"><span>{label}</span><div className="input-shell"><input type="number" value={value} min={min} max={max} step={step} onChange={e=>onChange(clamp(Number(e.target.value),min,max))}/>{suffix&&<em>{suffix}</em>}</div>{hint&&<small>{hint}</small>}</label>}
export default function Home(){
 const [round,setRound]=useState(10),[rarity,setRarity]=useState<Rarity>("Legendary"),[custom,setCustom]=useState<number|null>(null),[pool,setPool]=useState(18),[banished,setBanished]=useState(0),[weight,setWeight]=useState(1),[slots,setSlots]=useState(5),[locked,setLocked]=useState(0),[rerolls,setRerolls]=useState(5),[free,setFree]=useState(0);const base=custom??odds[round][rarity];
 const x=useMemo(()=>{const available=Math.max(1,pool-banished),active=Math.max(0,slots-locked),refreshes=rerolls+1,slot=(base/100)*(weight/available),one=1-Math.pow(1-slot,active),total=1-Math.pow(1-one,refreshes),expected=slot*active*refreshes,median=one>0?Math.ceil(Math.log(.5)/Math.log(1-one)):Infinity;return{active,refreshes,slot,one,total,expected,median}},[base,pool,banished,slots,locked,rerolls,weight]);const choose=(n:number)=>{setRound(n);setCustom(null)};
 return <main><header className="topbar"><a className="brand" href="#top"><span className="brand-mark">B</span><span>BRAWL SHOP LAB</span></a><span className="model-tag"><i/>COMMUNITY MODEL · 2026</span></header>
 <section className="hero" id="top"><div><p className="eyebrow">BACKPACK BRAWL · SHOP ODDS</p><h1>원하는 아이템,<br/><span>몇 번 굴려야 나올까?</span></h1></div><p className="hero-copy">라운드 등급 확률과 현재 아이템 풀을 조합해 목표 아이템의 출현 확률을 계산합니다.</p></section>
 <section className="workspace"><div className="controls-panel"><div className="section-head"><span>01</span><h2>목표 설정</h2></div><label className="field"><span>현재 라운드</span><div className="round-control"><button onClick={()=>choose(Math.max(1,round-1))}>−</button><strong>{round}<small>R</small></strong><button onClick={()=>choose(Math.min(21,round+1))}>＋</button></div><input className="range" type="range" min="1" max="21" value={round} onChange={e=>choose(Number(e.target.value))}/></label>
 <fieldset className="field rarity-field"><legend>목표 아이템 등급</legend><div className="rarity-grid">{rarities.map(r=><button key={r} className={rarity===r?"active":""} style={{"--rarity":colors[r]} as React.CSSProperties} onClick={()=>{setRarity(r);setCustom(null)}}><i/>{labels[r]}</button>)}</div></fieldset><div className="odds-strip"><div><span>{round}R {labels[rarity]} 등급 확률</span><strong>{base.toFixed(1)}%</strong></div><button onClick={()=>setCustom(custom===null?base:null)}>{custom===null?"직접 입력":"표 값 사용"}</button></div>{custom!==null&&<Field label="사용자 지정 등급 확률" value={custom} onChange={setCustom} max={100} step={.1} suffix="%"/>}
 <div className="section-head second"><span>02</span><h2>아이템 풀</h2></div><div className="field-grid"><Field label="같은 등급의 유효 아이템" value={pool} onChange={setPool} min={1} hint="공유 + 영웅 전용 중 현재 해금된 아이템"/><Field label="밴한 아이템" value={banished} onChange={n=>setBanished(Math.min(n,pool-1))} max={Math.max(0,pool-1)} hint="목표 아이템은 제외"/><Field label="목표 가중치" value={weight} onChange={setWeight} min={.01} max={10} step={.05} suffix="×" hint="균등 추첨은 1.0"/></div>
 <div className="section-head second"><span>03</span><h2>굴리기 조건</h2></div><div className="field-grid two"><Field label="상점 슬롯" value={slots} onChange={setSlots} min={1} max={10}/><Field label="잠근 슬롯" value={locked} onChange={n=>setLocked(Math.min(n,slots))} max={slots}/><Field label="리롤 횟수" value={rerolls} onChange={setRerolls} max={100}/><Field label="무료 리롤" value={free} onChange={setFree} max={rerolls}/></div></div>
 <aside className="results-panel"><div className="result-top"><span>최종 등장 확률</span><span className="live-dot">LIVE</span></div><div className="probability">{pct(x.total,1)}</div><p><b>{x.refreshes}회</b>의 상점, 총 <b>{x.active*x.refreshes}칸</b>에서 목표 아이템을 한 번 이상 볼 확률</p><div className="meter"><span style={{width:`${Math.min(100,x.total*100)}%`}}/></div><div className="milestones"><span>0</span><span>25</span><span>50</span><span>75</span><span>100%</span></div><div className="stat-grid"><article><span>한 슬롯</span><strong>{pct(x.slot)}</strong><small>등급 × 풀 내 선택</small></article><article><span>상점 1회</span><strong>{pct(x.one)}</strong><small>{x.active}개 활성 슬롯</small></article><article><span>기대 등장 수</span><strong>{x.expected.toFixed(2)}</strong><small>평균적인 출현 횟수</small></article><article><span>리롤 비용</span><strong>{rollCost(rerolls,free)}G</strong><small>무료 리롤 {free}회 반영</small></article></div><div className="readout"><span>50% 도달 예상</span><strong>{Number.isFinite(x.median)?`상점 ${x.median}회`:"도달 불가"}</strong></div><div className="formula-box"><span>계산식</span><code>P(슬롯) = 등급 확률 × 목표 가중치 ÷ 유효 풀</code><code>P(최소 1회) = 1 − (1 − P슬롯)<sup>활성 슬롯 × 상점 횟수</sup></code></div></aside></section>
 <section className="reference"><div className="reference-copy"><p className="eyebrow">REFERENCE TABLE</p><h2>라운드별 등급 확률</h2><p>커뮤니티에 공개된 표를 기본값으로 사용합니다. 패치나 게임 내 보정이 있다면 위의 ‘직접 입력’으로 현재 표시값을 넣으세요.</p></div><div className="table-wrap"><table><thead><tr><th>R</th>{rarities.map(r=><th key={r}>{labels[r]}</th>)}</tr></thead><tbody>{Object.entries(odds).map(([r,row])=><tr key={r} className={Number(r)===round?"selected":""} onClick={()=>choose(Number(r))}><td>{r}</td>{rarities.map(k=><td key={k}>{row[k]}%</td>)}</tr>)}</tbody></table></div></section>
 <section className="notice"><strong>모델 범위</strong><p>등급을 먼저 뽑고 같은 등급 풀에서 균등 추첨한다고 가정합니다. 이미 본 아이템의 확률 감소, 가방 pity, 클로버, 특정 타입 증가, 첫 상점 제한과 특수 상점은 자동 반영하지 않습니다. 해당 효과는 풀 크기와 목표 가중치로 조정할 수 있습니다.</p></section><footer><span>BRAWL SHOP LAB</span><span>비공식 커뮤니티 계산기 · 게임 내 표시값을 우선하세요</span></footer></main>}
